name: rail_lens
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.0+2
  rxdart: ^0.22.0
  backdrop: ^0.1.8
  carousel_slider: ^1.3.0
  toast: ^0.1.3
  shimmer: ^1.0.0
  image_picker: ^0.4.12
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+1
  path_provider: ^1.1.0
#  sqflite:
#  path:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rounded_floating_app_bar: 0.1.0
  image: ^2.1.4

dev_dependencies:
  dotted_border: ^0.1.1
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/circ.png
    - assets/icons/face.png
    - assets/icons/agra.jpg
    - assets/icons/food.png
    - assets/icons/gear.png
    - assets/icons/tube.png
    - assets/icons/platform.png
    - assets/icons/mslefemsle.png
    - assets/icons/taj.png
    - assets/icons/info.png
    - assets/icons/elevator.png
    - assets/icons/bf.png
    - assets/icons/stair.png
    - assets/icons/waitingroom.png
    - assets/icons/logout.png
    - assets/icons/search.png
    - assets/icons/add.png
    - assets/icons/galler.png
    - assets/icons/ina.png




  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
